import { articleService } from '@/modules/domains/provider';
import { Backdrop, CircularProgress } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const articleHooks = articleService.useGetAllArticle();
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Backdrop open={articleHooks.isLoading} color={'gray'}>
            <CircularProgress color="inherit" />
          </Backdrop>
          {articleHooks.data.map((ele) => {
            return (
              <>
                <p>{ele.title}</p>
                <p>{ele.content}</p>
              </>
            );
          })}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
